version: '2'
services:
 mongodb:
    build: ./docker_mongo
    ports:
      - "27017:27017"
 celery:
   build: .
   command: celery -A md5_web_service worker -l info --concurrency=2
   volumes:
     - .:/code
   links:
     - mongodb
 web:
   build: .
#   command: python3 manage.py test
   command: python3 manage.py runserver 0.0.0.0:80
   volumes:
     - .:/code
   ports:
     - "80:80"
   links:
     - mongodb
     - celery